apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-server
spec:
  ports:
    - port: {{ .Values.http.port }}
      targetPort: {{ .Values.http.targetPort }}
  selector:
    app: {{ .Release.Name }}-server
