image:
  repository: yashverma03/learning-backend
  tag: latest

http:
  port: 3000
  targetPort: 3000

env:
  # App config
  PORT: 3000
  NODE_ENV: local

  # Database config
  DB_HOST: chart-backend-db
  DB_USERNAME:
  DB_PASSWORD:
  DB_DATABASE: learning-local
  DB_ENTITIES: dist/entities/*.{ts,js}
  DB_ENTITIES_FOR_CLI: src/entities/*.{ts,js}
  DB_MIGRATIONS: dist/migrations/*.{ts,js}
  DB_MIGRATIONS_FOR_CLI: src/migrations/*.{ts,js}
  DB_SSL: true

  # AWS
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
